//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedRose.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementalTyping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElementalTyping()
        {
            this.Pokemons = new HashSet<Pokemon>();
        }
    
        public int ElementalTypingId { get; set; }
        public int PrimaryTypingId { get; set; }
        public Nullable<int> SecondaryTypingId { get; set; }
    
        public virtual PrimaryTyping PrimaryTyping { get; set; }
        public virtual SecondaryTyping SecondaryTyping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pokemon> Pokemons { get; set; }
    }
}
