//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedRose.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int PokemonId { get; set; }
        public string PokemonName { get; set; }
        public int ElementalTypingId { get; set; }
        public int FastAttackId { get; set; }
        public int ChargedAttackId { get; set; }
    
        public virtual ChargedAttack ChargedAttack { get; set; }
        public virtual ElementalTyping ElementalTyping { get; set; }
        public virtual FastAttack FastAttack { get; set; }
    }
}
